Source/Agatha.DVDRental.Operational.UI/Controllers/AddFilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Agatha.DVDRental.Fulfillment.ApplicationService.BusinessUseCases;
using Agatha.DVDRental.Infrastructure;
using Agatha.DVDRental.Operational.ApplicationService;
using Agatha.DVDRental.Operational.UI.Models;

namespace Agatha.DVDRental.Operational.UI.Controllers
{
    public class AddFilmController : Controller
    {       
        private readonly Application _application;

        public AddFilmController(Application application)
        {    
            _application = application;
        }

        //
        // GET: /AddFilm/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FilmModel filmModel)
        {           
            _application.action_request_to(new AddFilmToCatalogue(){ReleaseDate = DateTime.Now, Title = filmModel.Title});

            return RedirectToAction("FilmAdded", new { Title = filmModel.Title });
        }
       
        public ActionResult FilmAdded(String title)
        {
            var filmAdded = new FilmAddedModel();
            filmAdded.Title = title;

            return View(filmAdded);
        }
    }
}

Source/Agatha.DVDRental.Operational.UI/Views/AddFilm/FilmAdded.cshtml
@model Agatha.DVDRental.Operational.UI.Models.FilmAddedModel

<div class="alert alert-success">
    <p><b>Film Added</b>
        A film with the title <i>@Model.Title</i> has been added.
    </p>
</div>

<p>  @Html.ActionLink("Add another film?", "Index", "AddFilm")</p>

Source/Agatha.DVDRental.Operational.UI/Views/AddFilm/Index.cshtml
@model Agatha.DVDRental.Operational.UI.Models.FilmModel

@{
    ViewBag.Title = "title";
}

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true, "Film creation was unsuccessful. Please correct the errors and try again.")
    <div>
        <fieldset>
            <legend>Film Information</legend>

            <div class="editor-label">
                @Html.LabelFor(m => m.Title)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Title)
                @Html.ValidationMessageFor(m => m.Title)
            </div>                       

            <p>
                <input type="submit" value="Add Film" />
            </p>
        </fieldset>
    </div>
}