Source/Agatha.DVDRental.Operational.UI/Controllers/ReturnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Agatha.DVDRental.Fulfillment.ApplicationService.BusinessUseCases;
using Agatha.DVDRental.Infrastructure;
using Agatha.DVDRental.Operational.ApplicationService;

namespace Agatha.DVDRental.Operational.UI.Controllers
{
    public class ReturnsController : Controller
    {
        private OperationService _operationService;
        private readonly Application _application;

        public ReturnsController(OperationService operationService, Application application)
        {
            _operationService = operationService;
            _application = application;
        }

        //
        // GET: /Returns/

        public ActionResult Index()
        {
            var returns = _operationService.ViewAllPotentialReturns();

            return View(returns);
        }

        public ActionResult Process(int DvdId)
        {
            _application.action_request_to(new ReturnAFilm() {DvdId = DvdId});

            return RedirectToAction("ReturnProcessed");
        }

        public ActionResult ReturnProcessed()
        {
            return View();
        }
    }
}

Source/Agatha.DVDRental.Operational.UI/Views/Returns/Index.cshtml
@using Agatha.DVDRental.Fulfillment.Model.Stock
@model System.Collections.Generic.IEnumerable<Agatha.DVDRental.Fulfillment.Model.Stock.Dvd>

<div class="row-fluid">  
    <div class="span9">
         @foreach (Dvd dvdOnLoan in Model)
         {
             <h3>DvdId: @dvdOnLoan.Id</h3>             
             <p>On Loan to: @dvdOnLoan.CurrentLoan.SubscriptionId</p>
             <p>Date loaned out : @dvdOnLoan.CurrentLoan.DateLoanedOut</p>   
             
             using (Html.BeginForm("Process", "Returns"))
             {                                                                              
                    <input type="hidden" name="DvdId" value="@dvdId"/>                             
                    <p><input class="btn" value="Process Return" type="submit" /></p>                 
             }
             
             <hr/>
         } 
    </div>
    
    
</div>

Source/Agatha.DVDRental.Operational.UI/Views/Returns/ReturnProcessed.cshtml
@model dynamic

<div class="alert alert-success">
    <p><b>Return Processed</b>
        The film has been processed.
    </p>
</div>