Source/Agatha.DVDRental.Ui/Controllers/RentalHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Agatha.DVDRental.Public.ApplicationService;
using Agatha.DVDRental.Subscription.Model.RentalHistory;

namespace Agatha.DVDRental.Ui.Controllers
{
    public class RentalHistoryController : Controller
    {
         private readonly RentingService _renting;

         public RentalHistoryController(RentingService renting)
        {
            _renting = renting;            
        }

        //
        // GET: /RentalHistory/

        public ActionResult Index()
        {
            IEnumerable<Rental> rentalHistory =_renting.GetRentalHistoryFor(User.Identity.Name);

            return View(rentalHistory);
        }

    }
}

Source/Agatha.DVDRental.Ui/Controllers/RentalListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Agatha.DVDRental.Infrastructure;
using Agatha.DVDRental.Public.ApplicationService;
using System.Web.Security;
using Agatha.DVDRental.Subscription.ApplicationService.BusinessUseCases;
using Agatha.DVDRental.Subscription.Model.Subscriptions;

namespace Agatha.DVDRental.Ui.Controllers
{
    public class RentalListController : Controller
    {
        private readonly RentingService _renting;
        private readonly Application _application;
        private ISubscriptionRepository _subscriptionRepository;

        public RentalListController(RentingService renting, Application application, ISubscriptionRepository subscriptionRepository)
        {
            _renting = renting;
            _application = application;
            _subscriptionRepository = subscriptionRepository;
        }

        //
        // GET: /RentalRequestList/

        public ActionResult Index()
        {
            var rentalList = _renting.ViewRentalListFor(User.Identity.Name);

            return View(rentalList);
        }

        [HttpPost]
        public ActionResult AddFilmToList(int filmId)
        {                                   
             var subscription = _subscriptionRepository.FindBy(User.Identity.Name);

             _application.action_request_to(new CustomerWantsToRentAFim() { FilmId = filmId, SubscriptionId = subscription.Id });

            return RedirectToAction("Index", "Films");
        }

        [HttpPost]
        public ActionResult RemoveFilmFromList(int filmId)
        {            
            var subscription = _subscriptionRepository.FindBy(User.Identity.Name);

            _application.action_request_to(new CustomerIsNotInterestedInRentingThisFim() { FilmId = filmId, SubscriptionId = subscription.Id });

            return RedirectToAction("Index", "Films");
        }

    
    }
}

Source/Agatha.DVDRental.Ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
        <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 60px;
      }

      /* Custom container */
      .container {
        margin: 0 auto;
        max-width: 1000px;
      }
      .container > hr {
        margin: 60px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 80px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 100px;
        line-height: 1;
      }
      .jumbotron .lead {
        font-size: 24px;
        line-height: 1.25;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }


      /* Customize the navbar links to be fill the entire space of the .navbar */
      .navbar .navbar-inner {
        padding: 0;
      }
      .navbar .nav {
        margin: 0;
        display: table;
        width: 100%;
      }
      .navbar .nav li {
        display: table-cell;
        width: 1%;
        float: none;
      }
      .navbar .nav li a {
        font-weight: bold;
        text-align: center;
        border-left: 1px solid rgba(255,255,255,.75);
        border-right: 1px solid rgba(0,0,0,.1);
      }
      .navbar .nav li:first-child a {
        border-left: 0;
        border-radius: 3px 0 0 3px;
      }
      .navbar .nav li:last-child a {
        border-right: 0;
        border-radius: 0 3px 3px 0;
      }
    </style>
</head>
     <div class="container">
         <div class="masthead">
             <h3 class="muted">Agathas Film Rentals</h3>
             <div class="navbar">
                 <div class="navbar-inner">
                     <div class="container">
                         <ul class="nav">
                             <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                             <li>@Html.ActionLink("Films", "Index", "Films")</li>                             
                             <li><a href="#">How it works</a></li>
                            
                                @if (Request.IsAuthenticated)
                                {
                                    <li>@Html.ActionLink("Rental List", "Index", "RentalList")</li>
                                    <li>@Html.ActionLink("Rental History", "Index", "RentalHistory")</li>
                                    <li>@Html.ActionLink("Log Off", "LogOff", "Account")</li>
                                }
                                else
                                {
                                    <li>@Html.ActionLink("Log On", "LogOn", "Account")</li>
                                }                 
                             
                         </ul>
                     </div>
                 </div>
             </div>
             <!-- /.navbar -->
         </div>
         
                               
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>