Source/Agatha.DVDRental.Operational.UI/Controllers/PickController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Agatha.DVDRental.Fulfillment.ApplicationService.BusinessUseCases;
using Agatha.DVDRental.Fulfillment.Model.Fulfilment;
using Agatha.DVDRental.Infrastructure;
using Agatha.DVDRental.Operational.ApplicationService;
using Agatha.DVDRental.Operational.ApplicationService.ApplicationViews;
using Agatha.DVDRental.Operational.UI.Models;

namespace Agatha.DVDRental.Operational.UI.Controllers
{
    public class PickController : Controller
    {
        private OperationService _operationService;
        private readonly Application _application;

        public PickController(OperationService operationService, Application application)
        {
            _operationService = operationService;
            _application = application;
        }

        //
        // GET: /Pick/

        public ActionResult Index()
        {
            PickListView pickListView = _operationService.OperatorWantsToViewAssignedRentalAllocations("Scott");

            return View(pickListView);
        }

        [HttpPost]
        public ActionResult Assign()
        {            
            _application.action_request_to(new AssignRentalAllocationsToPicker() {PickerName = "Scott"});

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Dispatch(DvdAssignmentModel form)
        {            
            _application.action_request_to(new MarkRentalAllocationAsDispatched()
                                               {
                                                   PickerName = "Scott",
                                                   DvdId = form.DvdId,
                                                   FulfilmentRequestId = form.FulfilmentRequestId
                                               });

            return RedirectToAction("Index");
        }

    }
}

Source/Agatha.DVDRental.Operational.UI/Views/Pick/Index.cshtml
@using Agatha.DVDRental.Fulfillment.Model.Fulfilment
@using Agatha.DVDRental.Operational.ApplicationService.ApplicationViews
@model Agatha.DVDRental.Operational.ApplicationService.ApplicationViews.PickListView
      
      
<p>Pick List For: @Model.AssignedTo</p>
@using (Html.BeginForm("Assign", "Pick"))
{
    <p><input class="btn" value="Assign units &raquo;" type="submit" /></p>
}   
<hr/>
@foreach (PickRequestView request in Model.PickRequests)
     {         
        <div class="row-fluid">                              
         <div class="span6">
            <h3>@request.FilmTitle</h3>  
             <p>Requested On: @request.Requested</p>  
             <p>Dispatch to:</p>
             <p>221B Baker St,</p>
             <p>London</p>
             <p>Greater London</p>
             <p>NW1 6XE</p>                                                     
         </div>
    
        <div class="span6">           
            <h3>Fulfill</h3>
            @foreach(int dvdId in request.DvdIdsToFulfil)
            {                
                using (Html.BeginForm("Dispatch", "Pick"))
                {                                                          
                    <input type="hidden" name="FulfilmentRequestId" value="@request.FulfilmentRequestId"/>    
                    <input type="hidden" name="DvdId" value="@dvdId"/>                             
                    <p><input class="btn" value="SIMULATE FULFILLING WITH DVD ID: @dvdId" type="submit" /></p>                 
                }
            }
        </div>
        </div>
         <hr/>
     }     

 
             